//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DGNameVisibility {
            get {
                return ((bool)(this["DGNameVisibility"]));
            }
            set {
                this["DGNameVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGItemCodeVisibility {
            get {
                return ((bool)(this["DGItemCodeVisibility"]));
            }
            set {
                this["DGItemCodeVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGCountVisibility {
            get {
                return ((bool)(this["DGCountVisibility"]));
            }
            set {
                this["DGCountVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGLenghtVisibility {
            get {
                return ((bool)(this["DGLenghtVisibility"]));
            }
            set {
                this["DGLenghtVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGRetailVisibility {
            get {
                return ((bool)(this["DGRetailVisibility"]));
            }
            set {
                this["DGRetailVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGWholesaleVisibility {
            get {
                return ((bool)(this["DGWholesaleVisibility"]));
            }
            set {
                this["DGWholesaleVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGPurchaseDolPrice {
            get {
                return ((bool)(this["DGPurchaseDolPrice"]));
            }
            set {
                this["DGPurchaseDolPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGPurchaseUahPrice {
            get {
                return ((bool)(this["DGPurchaseUahPrice"]));
            }
            set {
                this["DGPurchaseUahPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGCountryVisibility {
            get {
                return ((bool)(this["DGCountryVisibility"]));
            }
            set {
                this["DGCountryVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double CurrencyExchangeDol {
            get {
                return ((double)(this["CurrencyExchangeDol"]));
            }
            set {
                this["CurrencyExchangeDol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user1 {
            get {
                return ((string)(this["user1"]));
            }
            set {
                this["user1"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s6Wn2AHNDDmyUocSBE+E2AphwopTh8qnPbxa1QJyU0w=")]
        public string dev1 {
            get {
                return ((string)(this["dev1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user2 {
            get {
                return ((string)(this["user2"]));
            }
            set {
                this["user2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_Date {
            get {
                return ((bool)(this["DGArrivals_Date"]));
            }
            set {
                this["DGArrivals_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_Number {
            get {
                return ((bool)(this["DGArrivals_Number"]));
            }
            set {
                this["DGArrivals_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_PurchaseTotal {
            get {
                return ((bool)(this["DGArrivals_PurchaseTotal"]));
            }
            set {
                this["DGArrivals_PurchaseTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_Supplier {
            get {
                return ((bool)(this["DGArrivals_Supplier"]));
            }
            set {
                this["DGArrivals_Supplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_Receiver {
            get {
                return ((bool)(this["DGArrivals_Receiver"]));
            }
            set {
                this["DGArrivals_Receiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_Wholesale {
            get {
                return ((bool)(this["DGArrivals_Wholesale"]));
            }
            set {
                this["DGArrivals_Wholesale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_Enterprise {
            get {
                return ((bool)(this["DGArrivals_Enterprise"]));
            }
            set {
                this["DGArrivals_Enterprise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGArrivals_User {
            get {
                return ((bool)(this["DGArrivals_User"]));
            }
            set {
                this["DGArrivals_User"] = value;
            }
        }
    }
}
